### ISSUE TITLE
Time In Message

### ISSUE THREAD

**Issue by amayer5125** [tomswartz07/AdventOfCodeLeaderboard#5]
Should we remove the time in the message since the time is displayed by Slack?

Maybe change it to something like "Current Standings:"

**Comment by tomswartz07** [comment]
Yeah, I had thought about that as I was implementing it.

The other drawback is that it doesn't use Slack's native `<!date>` tags, so if a viewer is in a different timezone, the message will be wrong.

Lets pull it out.
